import { type } from 'os'

export type CountryDataType = {
  code: string
  label?: string
  phone: string
  suggested?: boolean
  [key: string]: string | boolean | undefined
}

type CountryLabel = {
  [key: string]: { code: string; label: string; suggested?: boolean }[]
}

const countryDataBase: CountryDataType[] = [
  { code: 'AD', phone: '376' },
  {
    code: 'AE',

    phone: '971',
  },
  { code: 'AF', phone: '93' },
  {
    code: 'AG',

    phone: '1-268',
  },
  { code: 'AI', phone: '1-264' },
  { code: 'AL', phone: '355' },
  { code: 'AM', phone: '374' },
  { code: 'AO', phone: '244' },
  { code: 'AQ', phone: '672' },
  { code: 'AR', phone: '54' },
  { code: 'AS', phone: '1-684' },
  { code: 'AT', phone: '43' },
  {
    code: 'AU',

    phone: '61',
    suggested: true,
  },
  { code: 'AW', phone: '297' },
  { code: 'AX', phone: '358' },
  { code: 'AZ', phone: '994' },
  {
    code: 'BA',

    phone: '387',
  },
  { code: 'BB', phone: '1-246' },
  { code: 'BD', phone: '880' },
  { code: 'BE', phone: '32' },
  { code: 'BF', phone: '226' },
  { code: 'BG', phone: '359' },
  { code: 'BH', phone: '973' },
  { code: 'BI', phone: '257' },
  { code: 'BJ', phone: '229' },
  { code: 'BL', phone: '590' },
  { code: 'BM', phone: '1-441' },
  { code: 'BN', phone: '673' },
  { code: 'BO', phone: '591' },
  { code: 'BR', phone: '55' },
  { code: 'BS', phone: '1-242' },
  { code: 'BT', phone: '975' },
  { code: 'BV', phone: '47' },
  { code: 'BW', phone: '267' },
  { code: 'BY', phone: '375' },
  { code: 'BZ', phone: '501' },
  {
    code: 'CA',
    phone: '1',
    suggested: true,
  },
  {
    code: 'CC',
    phone: '61',
  },
  {
    code: 'CD',
    phone: '243',
  },
  {
    code: 'CF',
    phone: '236',
  },
  {
    code: 'CG',
    phone: '242',
  },
  { code: 'CH', phone: '41' },
  { code: 'CI', phone: '225' },
  { code: 'CK', phone: '682' },
  { code: 'CL', phone: '56' },
  { code: 'CM', phone: '237' },
  { code: 'CN', phone: '86' },
  { code: 'CO', phone: '57' },
  { code: 'CR', phone: '506' },
  { code: 'CU', phone: '53' },
  { code: 'CV', phone: '238' },
  { code: 'CW', phone: '599' },
  { code: 'CX', phone: '61' },
  { code: 'CY', phone: '357' },
  { code: 'CZ', phone: '420' },
  {
    code: 'DE',
    phone: '49',
    suggested: true,
  },
  { code: 'DJ', phone: '253' },
  { code: 'DK', phone: '45' },
  { code: 'DM', phone: '1-767' },
  {
    code: 'DO',
    phone: '1-809',
  },
  { code: 'DZ', phone: '213' },
  { code: 'EC', phone: '593' },
  { code: 'EE', phone: '372' },
  { code: 'EG', phone: '20' },
  { code: 'EH', phone: '212' },
  { code: 'ER', phone: '291' },
  { code: 'ES', phone: '34' },
  { code: 'ET', phone: '251' },
  { code: 'FI', phone: '358' },
  { code: 'FJ', phone: '679' },
  {
    code: 'FK',
    phone: '500',
  },
  {
    code: 'FM',
    phone: '691',
  },
  { code: 'FO', phone: '298' },
  {
    code: 'FR',
    phone: '33',
    suggested: true,
  },
  { code: 'GA', phone: '241' },
  { code: 'GB', phone: '44' },
  { code: 'GD', phone: '1-473' },
  { code: 'GE', phone: '995' },
  { code: 'GF', phone: '594' },
  { code: 'GG', phone: '44' },
  { code: 'GH', phone: '233' },
  { code: 'GI', phone: '350' },
  { code: 'GL', phone: '299' },
  { code: 'GM', phone: '220' },
  { code: 'GN', phone: '224' },
  { code: 'GP', phone: '590' },
  { code: 'GQ', phone: '240' },
  { code: 'GR', phone: '30' },
  {
    code: 'GS',
    phone: '500',
  },
  { code: 'GT', phone: '502' },
  { code: 'GU', phone: '1-671' },
  { code: 'GW', phone: '245' },
  { code: 'GY', phone: '592' },
  { code: 'HK', phone: '852' },
  {
    code: 'HM',
    phone: '672',
  },
  { code: 'HN', phone: '504' },
  { code: 'HR', phone: '385' },
  { code: 'HT', phone: '509' },
  { code: 'HU', phone: '36' },
  { code: 'ID', phone: '62' },
  { code: 'IE', phone: '353' },
  { code: 'IL', phone: '972' },
  { code: 'IM', phone: '44' },
  { code: 'IN', phone: '91' },
  {
    code: 'IO',
    phone: '246',
  },
  { code: 'IQ', phone: '964' },
  {
    code: 'IR',
    phone: '98',
  },
  { code: 'IS', phone: '354' },
  { code: 'IT', phone: '39' },
  { code: 'JE', phone: '44' },
  { code: 'JM', phone: '1-876' },
  { code: 'JO', phone: '962' },
  {
    code: 'JP',
    phone: '81',
    suggested: true,
  },
  { code: 'KE', phone: '254' },
  { code: 'KG', phone: '996' },
  { code: 'KH', phone: '855' },
  { code: 'KI', phone: '686' },
  { code: 'KM', phone: '269' },
  {
    code: 'KN',
    phone: '1-869',
  },
  {
    code: 'KP',
    label: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { code: 'KR', phone: '82' },
  { code: 'KW', phone: '965' },
  { code: 'KY', phone: '1-345' },
  { code: 'KZ', phone: '7' },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    phone: '856',
  },
  { code: 'LB', phone: '961' },
  { code: 'LC', phone: '1-758' },
  { code: 'LI', phone: '423' },
  { code: 'LK', phone: '94' },
  { code: 'LR', phone: '231' },
  { code: 'LS', phone: '266' },
  { code: 'LT', phone: '370' },
  { code: 'LU', phone: '352' },
  { code: 'LV', phone: '371' },
  { code: 'LY', phone: '218' },
  { code: 'MA', phone: '212' },
  { code: 'MC', phone: '377' },
  {
    code: 'MD',
    phone: '373',
  },
  { code: 'ME', phone: '382' },
  {
    code: 'MF',
    phone: '590',
  },
  { code: 'MG', phone: '261' },
  { code: 'MH', phone: '692' },
  {
    code: 'MK',

    phone: '389',
  },
  { code: 'ML', phone: '223' },
  { code: 'MM', phone: '95' },
  { code: 'MN', phone: '976' },
  { code: 'MO', phone: '853' },
  {
    code: 'MP',

    phone: '1-670',
  },
  { code: 'MQ', phone: '596' },
  { code: 'MR', phone: '222' },
  { code: 'MS', phone: '1-664' },
  { code: 'MT', phone: '356' },
  { code: 'MU', phone: '230' },
  { code: 'MV', phone: '960' },
  { code: 'MW', phone: '265' },
  { code: 'MX', phone: '52' },
  { code: 'MY', phone: '60' },
  { code: 'MZ', phone: '258' },
  { code: 'NA', phone: '264' },
  { code: 'NC', phone: '687' },
  { code: 'NE', phone: '227' },
  { code: 'NF', phone: '672' },
  { code: 'NG', phone: '234' },
  { code: 'NI', phone: '505' },
  { code: 'NL', phone: '31' },
  { code: 'NO', phone: '47' },
  { code: 'NP', phone: '977' },
  { code: 'NR', phone: '674' },
  { code: 'NU', phone: '683' },
  { code: 'NZ', phone: '64' },
  { code: 'OM', phone: '968' },
  { code: 'PA', phone: '507' },
  { code: 'PE', phone: '51' },
  { code: 'PF', phone: '689' },
  { code: 'PG', phone: '675' },
  { code: 'PH', phone: '63' },
  { code: 'PK', phone: '92' },
  { code: 'PL', phone: '48' },
  {
    code: 'PM',

    phone: '508',
  },
  { code: 'PN', phone: '870' },
  { code: 'PR', phone: '1' },
  {
    code: 'PS',

    phone: '970',
  },
  { code: 'PT', phone: '351' },
  { code: 'PW', phone: '680' },
  { code: 'PY', phone: '595' },
  { code: 'QA', phone: '974' },
  { code: 'RE', phone: '262' },
  { code: 'RO', phone: '40' },
  { code: 'RS', phone: '381' },
  { code: 'RU', phone: '7' },
  { code: 'RW', phone: '250' },
  { code: 'SA', phone: '966' },
  { code: 'SB', phone: '677' },
  { code: 'SC', phone: '248' },
  { code: 'SD', phone: '249' },
  { code: 'SE', phone: '46' },
  { code: 'SG', phone: '65' },
  { code: 'SH', phone: '290' },
  { code: 'SI', phone: '386' },
  {
    code: 'SJ',

    phone: '47',
  },
  { code: 'SK', phone: '421' },
  { code: 'SL', phone: '232' },
  { code: 'SM', phone: '378' },
  { code: 'SN', phone: '221' },
  { code: 'SO', phone: '252' },
  { code: 'SR', phone: '597' },
  { code: 'SS', phone: '211' },
  {
    code: 'ST',

    phone: '239',
  },
  { code: 'SV', phone: '503' },
  {
    code: 'SX',

    phone: '1-721',
  },
  {
    code: 'SY',

    phone: '963',
  },
  { code: 'SZ', phone: '268' },
  {
    code: 'TC',

    phone: '1-649',
  },
  { code: 'TD', phone: '235' },
  {
    code: 'TF',

    phone: '262',
  },
  { code: 'TG', phone: '228' },
  { code: 'TH', phone: '66' },
  { code: 'TJ', phone: '992' },
  { code: 'TK', phone: '690' },
  { code: 'TL', phone: '670' },
  { code: 'TM', phone: '993' },
  { code: 'TN', phone: '216' },
  { code: 'TO', phone: '676' },
  { code: 'TR', phone: '90' },
  {
    code: 'TT',

    phone: '1-868',
  },
  { code: 'TV', phone: '688' },
  {
    code: 'TW',

    phone: '886',
  },
  {
    code: 'TZ',

    phone: '255',
  },
  { code: 'UA', phone: '380' },
  { code: 'UG', phone: '256' },
  {
    code: 'US',

    phone: '1',
    suggested: true,
  },
  { code: 'UY', phone: '598' },
  { code: 'UZ', phone: '998' },
  {
    code: 'VA',

    phone: '379',
  },
  {
    code: 'VC',

    phone: '1-784',
  },
  { code: 'VE', phone: '58' },
  {
    code: 'VG',

    phone: '1-284',
  },
  {
    code: 'VI',

    phone: '1-340',
  },
  { code: 'VN', phone: '84' },
  { code: 'VU', phone: '678' },
  { code: 'WF', phone: '681' },
  { code: 'WS', phone: '685' },
  { code: 'XK', phone: '383' },
  { code: 'YE', phone: '967' },
  { code: 'YT', phone: '262' },
  { code: 'ZA', phone: '27' },
  { code: 'ZM', phone: '260' },
  { code: 'ZW', phone: '263' },
]

const countriesLabels: CountryLabel = {
  en: [
    { code: 'AD', label: 'Andorra' },
    {
      code: 'AE',
      label: 'United Arab Emirates',
    },
    { code: 'AF', label: 'Afghanistan' },
    {
      code: 'AG',
      label: 'Antigua and Barbuda',
    },
    { code: 'AI', label: 'Anguilla' },
    { code: 'AL', label: 'Albania' },
    { code: 'AM', label: 'Armenia' },
    { code: 'AO', label: 'Angola' },
    { code: 'AQ', label: 'Antarctica' },
    { code: 'AR', label: 'Argentina' },
    { code: 'AS', label: 'American Samoa' },
    { code: 'AT', label: 'Austria' },
    {
      code: 'AU',
      label: 'Australia',
    },
    { code: 'AW', label: 'Aruba' },
    { code: 'AX', label: 'Alland Islands' },
    { code: 'AZ', label: 'Azerbaijan' },
    {
      code: 'BA',
      label: 'Bosnia and Herzegovina',
    },
    { code: 'BB', label: 'Barbados' },
    { code: 'BD', label: 'Bangladesh' },
    { code: 'BE', label: 'Belgium' },
    { code: 'BF', label: 'Burkina Faso' },
    { code: 'BG', label: 'Bulgaria' },
    { code: 'BH', label: 'Bahrain' },
    { code: 'BI', label: 'Burundi' },
    { code: 'BJ', label: 'Benin' },
    { code: 'BL', label: 'Saint Barthelemy' },
    { code: 'BM', label: 'Bermuda' },
    { code: 'BN', label: 'Brunei Darussalam' },
    { code: 'BO', label: 'Bolivia' },
    { code: 'BR', label: 'Brazil' },
    { code: 'BS', label: 'Bahamas' },
    { code: 'BT', label: 'Bhutan' },
    { code: 'BV', label: 'Bouvet Island' },
    { code: 'BW', label: 'Botswana' },
    { code: 'BY', label: 'Belarus' },
    { code: 'BZ', label: 'Belize' },
    {
      code: 'CA',
      label: 'Canada',
    },
    {
      code: 'CC',
      label: 'Cocos (Keeling) Islands',
    },
    {
      code: 'CD',
      label: 'Congo, Democratic Republic of the',
    },
    {
      code: 'CF',
      label: 'Central African Republic',
    },
    {
      code: 'CG',
      label: 'Congo, Republic of the',
    },
    { code: 'CH', label: 'Switzerland' },
    { code: 'CI', label: "Cote d'Ivoire" },
    { code: 'CK', label: 'Cook Islands' },
    { code: 'CL', label: 'Chile' },
    { code: 'CM', label: 'Cameroon' },
    { code: 'CN', label: 'China' },
    { code: 'CO', label: 'Colombia' },
    { code: 'CR', label: 'Costa Rica' },
    { code: 'CU', label: 'Cuba' },
    { code: 'CV', label: 'Cape Verde' },
    { code: 'CW', label: 'Curacao' },
    { code: 'CX', label: 'Christmas Island' },
    { code: 'CY', label: 'Cyprus' },
    { code: 'CZ', label: 'Czech Republic' },
    {
      code: 'DE',
      label: 'Germany',


    },
    { code: 'DJ', label: 'Djibouti' },
    { code: 'DK', label: 'Denmark' },
    { code: 'DM', label: 'Dominica' },
    {
      code: 'DO',
      label: 'Dominican Republic',
    },
    { code: 'DZ', label: 'Algeria' },
    { code: 'EC', label: 'Ecuador' },
    { code: 'EE', label: 'Estonia' },
    { code: 'EG', label: 'Egypt' },
    { code: 'EH', label: 'Western Sahara' },
    { code: 'ER', label: 'Eritrea' },
    { code: 'ES', label: 'Spain' },
    { code: 'ET', label: 'Ethiopia' },
    { code: 'FI', label: 'Finland' },
    { code: 'FJ', label: 'Fiji' },
    {
      code: 'FK',
      label: 'Falkland Islands (Malvinas)',
    },
    {
      code: 'FM',
      label: 'Micronesia, Federated States of',
    },
    { code: 'FO', label: 'Faroe Islands' },
    {
      code: 'FR',
      label: 'France',


    },
    { code: 'GA', label: 'Gabon' },
    { code: 'GB', label: 'United Kingdom' },
    { code: 'GD', label: 'Grenada' },
    { code: 'GE', label: 'Georgia' },
    { code: 'GF', label: 'French Guiana' },
    { code: 'GG', label: 'Guernsey' },
    { code: 'GH', label: 'Ghana' },
    { code: 'GI', label: 'Gibraltar' },
    { code: 'GL', label: 'Greenland' },
    { code: 'GM', label: 'Gambia' },
    { code: 'GN', label: 'Guinea' },
    { code: 'GP', label: 'Guadeloupe' },
    { code: 'GQ', label: 'Equatorial Guinea' },
    { code: 'GR', label: 'Greece' },
    {
      code: 'GS',
      label: 'South Georgia and the South Sandwich Islands',
    },
    { code: 'GT', label: 'Guatemala' },
    { code: 'GU', label: 'Guam' },
    { code: 'GW', label: 'Guinea-Bissau' },
    { code: 'GY', label: 'Guyana' },
    { code: 'HK', label: 'Hong Kong' },
    {
      code: 'HM',
      label: 'Heard Island and McDonald Islands',
    },
    { code: 'HN', label: 'Honduras' },
    { code: 'HR', label: 'Croatia' },
    { code: 'HT', label: 'Haiti' },
    { code: 'HU', label: 'Hungary' },
    { code: 'ID', label: 'Indonesia' },
    { code: 'IE', label: 'Ireland' },
    { code: 'IL', label: 'Israel' },
    { code: 'IM', label: 'Isle of Man' },
    { code: 'IN', label: 'India' },
    {
      code: 'IO',
      label: 'British Indian Ocean Territory',
    },
    { code: 'IQ', label: 'Iraq' },
    {
      code: 'IR',
      label: 'Iran, Islamic Republic of',
    },
    { code: 'IS', label: 'Iceland' },
    { code: 'IT', label: 'Italy' },
    { code: 'JE', label: 'Jersey' },
    { code: 'JM', label: 'Jamaica' },
    { code: 'JO', label: 'Jordan' },
    {
      code: 'JP',
      label: 'Japan',

  
    },
    { code: 'KE', label: 'Kenya' },
    { code: 'KG', label: 'Kyrgyzstan' },
    { code: 'KH', label: 'Cambodia' },
    { code: 'KI', label: 'Kiribati' },
    { code: 'KM', label: 'Comoros' },
    {
      code: 'KN',
      label: 'Saint Kitts and Nevis',
    },
    {
      code: 'KP',
      label: "Korea, Democratic People's Republic of",
    },
    { code: 'KR', label: 'Korea, Republic of' },
    { code: 'KW', label: 'Kuwait' },
    { code: 'KY', label: 'Cayman Islands' },
    { code: 'KZ', label: 'Kazakhstan' },
    {
      code: 'LA',
      label: "Lao People's Democratic Republic",
    },
    { code: 'LB', label: 'Lebanon' },
    { code: 'LC', label: 'Saint Lucia' },
    { code: 'LI', label: 'Liechtenstein' },
    { code: 'LK', label: 'Sri Lanka' },
    { code: 'LR', label: 'Liberia' },
    { code: 'LS', label: 'Lesotho' },
    { code: 'LT', label: 'Lithuania' },
    { code: 'LU', label: 'Luxembourg' },
    { code: 'LV', label: 'Latvia' },
    { code: 'LY', label: 'Libya' },
    { code: 'MA', label: 'Morocco' },
    { code: 'MC', label: 'Monaco' },
    {
      code: 'MD',
      label: 'Moldova, Republic of',
    },
    { code: 'ME', label: 'Montenegro' },
    {
      code: 'MF',
      label: 'Saint Martin (French part)',
    },
    { code: 'MG', label: 'Madagascar' },
    { code: 'MH', label: 'Marshall Islands' },
    {
      code: 'MK',
      label: 'Macedonia, the Former Yugoslav Republic of',
    },
    { code: 'ML', label: 'Mali' },
    { code: 'MM', label: 'Myanmar' },
    { code: 'MN', label: 'Mongolia' },
    { code: 'MO', label: 'Macao' },
    {
      code: 'MP',
      label: 'Northern Mariana Islands',
    },
    { code: 'MQ', label: 'Martinique' },
    { code: 'MR', label: 'Mauritania' },
    { code: 'MS', label: 'Montserrat' },
    { code: 'MT', label: 'Malta' },
    { code: 'MU', label: 'Mauritius' },
    { code: 'MV', label: 'Maldives' },
    { code: 'MW', label: 'Malawi' },
    { code: 'MX', label: 'Mexico' },
    { code: 'MY', label: 'Malaysia' },
    { code: 'MZ', label: 'Mozambique' },
    { code: 'NA', label: 'Namibia' },
    { code: 'NC', label: 'New Caledonia' },
    { code: 'NE', label: 'Niger' },
    { code: 'NF', label: 'Norfolk Island' },
    { code: 'NG', label: 'Nigeria' },
    { code: 'NI', label: 'Nicaragua' },
    { code: 'NL', label: 'Netherlands' },
    { code: 'NO', label: 'Norway' },
    { code: 'NP', label: 'Nepal' },
    { code: 'NR', label: 'Nauru' },
    { code: 'NU', label: 'Niue' },
    { code: 'NZ', label: 'New Zealand' },
    { code: 'OM', label: 'Oman' },
    { code: 'PA', label: 'Panama' },
    { code: 'PE', label: 'Peru' },
    { code: 'PF', label: 'French Polynesia' },
    { code: 'PG', label: 'Papua New Guinea' },
    { code: 'PH', label: 'Philippines' },
    { code: 'PK', label: 'Pakistan' },
    { code: 'PL', label: 'Poland' },
    {
      code: 'PM',
      label: 'Saint Pierre and Miquelon',
    },
    { code: 'PN', label: 'Pitcairn' },
    { code: 'PR', label: 'Puerto Rico' },
    {
      code: 'PS',
      label: 'Palestine, State of',
    },
    { code: 'PT', label: 'Portugal' },
    { code: 'PW', label: 'Palau' },
    { code: 'PY', label: 'Paraguay' },
    { code: 'QA', label: 'Qatar' },
    { code: 'RE', label: 'Reunion' },
    { code: 'RO', label: 'Romania' },
    { code: 'RS', label: 'Serbia' },
    { code: 'RU', label: 'Russian Federation' },
    { code: 'RW', label: 'Rwanda' },
    { code: 'SA', label: 'Saudi Arabia' },
    { code: 'SB', label: 'Solomon Islands' },
    { code: 'SC', label: 'Seychelles' },
    { code: 'SD', label: 'Sudan' },
    { code: 'SE', label: 'Sweden' },
    { code: 'SG', label: 'Singapore' },
    { code: 'SH', label: 'Saint Helena' },
    { code: 'SI', label: 'Slovenia' },
    {
      code: 'SJ',
      label: 'Svalbard and Jan Mayen',
    },
    { code: 'SK', label: 'Slovakia' },
    { code: 'SL', label: 'Sierra Leone' },
    { code: 'SM', label: 'San Marino' },
    { code: 'SN', label: 'Senegal' },
    { code: 'SO', label: 'Somalia' },
    { code: 'SR', label: 'Surilabel' },
    { code: 'SS', label: 'South Sudan' },
    {
      code: 'ST',
      label: 'Sao Tome and Principe',
    },
    { code: 'SV', label: 'El Salvador' },
    {
      code: 'SX',
      label: 'Sint Maarten (Dutch part)',
    },
    {
      code: 'SY',
      label: 'Syrian Arab Republic',
    },
    { code: 'SZ', label: 'Swaziland' },
    {
      code: 'TC',
      label: 'Turks and Caicos Islands',
    },
    { code: 'TD', label: 'Chad' },
    {
      code: 'TF',
      label: 'French Southern Territories',
    },
    { code: 'TG', label: 'Togo' },
    { code: 'TH', label: 'Thailand' },
    { code: 'TJ', label: 'Tajikistan' },
    { code: 'TK', label: 'Tokelau' },
    { code: 'TL', label: 'Timor-Leste' },
    { code: 'TM', label: 'Turkmenistan' },
    { code: 'TN', label: 'Tunisia' },
    { code: 'TO', label: 'Tonga' },
    { code: 'TR', label: 'Turkey' },
    {
      code: 'TT',
      label: 'Trinidad and Tobago',
    },
    { code: 'TV', label: 'Tuvalu' },
    {
      code: 'TW',
      label: 'Taiwan, Republic of China',
    },
    {
      code: 'TZ',
      label: 'United Republic of Tanzania',
    },
    { code: 'UA', label: 'Ukraine' },
    { code: 'UG', label: 'Uganda' },
    {
      code: 'US',
      label: 'United States',


    },
    { code: 'UY', label: 'Uruguay' },
    { code: 'UZ', label: 'Uzbekistan' },
    {
      code: 'VA',
      label: 'Holy See (Vatican City State)',
    },
    {
      code: 'VC',
      label: 'Saint Vincent and the Grenadines',
    },
    { code: 'VE', label: 'Venezuela' },
    {
      code: 'VG',
      label: 'British Virgin Islands',
    },
    {
      code: 'VI',
      label: 'US Virgin Islands',
    },
    { code: 'VN', label: 'Vietnam' },
    { code: 'VU', label: 'Vanuatu' },
    { code: 'WF', label: 'Wallis and Futuna' },
    { code: 'WS', label: 'Samoa' },
    { code: 'XK', label: 'Kosovo' },
    { code: 'YE', label: 'Yemen' },
    { code: 'YT', label: 'Mayotte' },
    { code: 'ZA', label: 'South Africa' },
    { code: 'ZM', label: 'Zambia' },
    { code: 'ZW', label: 'Zimbabwe' },
  ],
  he: [
    { code: 'AD', label: 'אנדורה' },
    { code: 'AE', label: 'איחוד האמירויות הערביות' },
    { code: 'AF', label: 'אפגניסטן' },
    { code: 'AG', label: 'אנטיגואה וברבודה' },
    { code: 'AI', label: 'אנגילה' },
    { code: 'AL', label: 'אלבניה' },
    { code: 'AM', label: 'ארמניה' },
    { code: 'AO', label: 'אנגולה' },
    { code: 'AQ', label: 'אנטארקטיקה' },
    { code: 'AR', label: 'ארגנטינה' },
    { code: 'AS', label: 'סמואה האמריקנית' },
    { code: 'AT', label: 'אוסטריה' },
    { code: 'AU', label: 'אוסטרליה',  },
    { code: 'AW', label: 'ארובה' },
    { code: 'AX', label: 'איי אולנד' },
    { code: 'AZ', label: 'אזרבייג׳ן' },
    { code: 'BA', label: 'בוסניה והרצגובינה' },
    { code: 'BB', label: 'ברבדוס' },
    { code: 'BD', label: 'בנגלדש' },
    { code: 'BE', label: 'בלגיה' },
    { code: 'BF', label: 'בורקינה פאסו' },
    { code: 'BG', label: 'בולגריה' },
    { code: 'BH', label: 'בחריין' },
    { code: 'BI', label: 'בורונדי' },
    { code: 'BJ', label: 'בנין' },
    { code: 'BL', label: 'סנט ברתולומיאו' },
    { code: 'BM', label: 'ברמודה' },
    { code: 'BN', label: 'ברוניי' },
    { code: 'BO', label: 'בוליביה' },
    { code: 'BR', label: 'ברזיל' },
    { code: 'BS', label: 'איי בהאמה' },
    { code: 'BT', label: 'בהוטן' },
    { code: 'BV', label: 'איי בובה' },
    { code: 'BW', label: 'בוטסואנה' },
    { code: 'BY', label: 'בלארוס' },
    { code: 'BZ', label: 'בליז' },
    { code: 'CA', label: 'קנדה',  },
    { code: 'CC', label: 'איי קוקוס (קילינג)' },
    { code: 'CD', label: 'קונגו, דמוקרטית של' },
    { code: 'CF', label: 'הרפובליקה המרכז-אפריקאית' },
    { code: 'CG', label: 'קונגו, רפובליקה של' },
    { code: 'CH', label: 'שווייץ' },
    { code: 'CI', label: 'חוף השנהב' },
    { code: 'CK', label: 'איי קוק' },
    { code: 'CL', label: 'צ׳ילה' },
    { code: 'CM', label: 'קמרון' },
    { code: 'CN', label: 'סין' },
    { code: 'CO', label: 'קולומביה' },
    { code: 'CR', label: 'קוסטה ריקה' },
    { code: 'CU', label: 'קובה' },
    { code: 'CV', label: 'כף ורדה' },
    { code: 'CW', label: 'קוראסאו' },
    { code: 'CX', label: 'אי חג המולד' },
    { code: 'CY', label: 'קפריסין' },
    { code: 'CZ', label: 'צ׳כיה' },
    { code: 'DE', label: 'גרמניה', },
    { code: 'DJ', label: 'ג׳יבוטי' },
    { code: 'DK', label: 'דנמרק' },
    { code: 'DM', label: 'דומיניקה' },
    { code: 'DO', label: 'הרפובליקה הדומיניקנית' },
    { code: 'DZ', label: 'אלג׳יריה' },
    { code: 'EC', label: 'אקוודור' },
    { code: 'EE', label: 'אסטוניה' },
    { code: 'EG', label: 'מצרים' },
    { code: 'EH', label: 'סהרה המערבית' },
    { code: 'ER', label: 'אריתריאה' },
    { code: 'ES', label: 'ספרד' },
    { code: 'ET', label: 'אתיופיה' },
    { code: 'FI', label: 'פינלנד' },
    { code: 'FJ', label: 'פיג׳י' },
    { code: 'FK', label: 'איי פוקלנד (מלווינס)' },
    { code: 'FM', label: 'מיקרונזיה, מדינות הפדרציה של' },
    { code: 'FO', label: 'איי פארו' },
    { code: 'FR', label: 'צרפת', },
    { code: 'GA', label: 'גאבון' },
    { code: 'GB', label: 'הממלכה המאוחדת' },
    { code: 'GD', label: 'גרנדה' },
    { code: 'GE', label: 'גאורגיה' },
    { code: 'GF', label: 'גיאנה הצרפתית' },
    { code: 'GG', label: 'גרנזי' },
    { code: 'GH', label: 'גאנה' },
    { code: 'GI', label: 'גיברלטר' },
    { code: 'GL', label: 'גרינלנד' },
    { code: 'GM', label: 'גמביה' },
    { code: 'GN', label: 'גיניאה' },
    { code: 'GP', label: 'גוואדלופ' },
    { code: 'GQ', label: 'גיניאה המשוונית' },
    { code: 'GR', label: 'יוון' },
    { code: 'GS', label: 'גיאורגיה הדרומית ואיי סנדוויץ׳ הדרומיים' },
    { code: 'GT', label: 'גואטמלה' },
    { code: 'GU', label: 'גואם' },
    { code: 'GW', label: 'גיניאה ביסאו' },
    { code: 'GY', label: 'גיאנה' },
    { code: 'HK', label: 'הונג קונג' },
    { code: 'HM', label: 'איי הרד ואיי מקדונלד' },
    { code: 'HN', label: 'הונדורס' },
    { code: 'HR', label: 'קרואטיה' },
    { code: 'HT', label: 'האיטי' },
    { code: 'HU', label: 'הונגריה' },
    { code: 'ID', label: 'אינדונזיה' },
    { code: 'IE', label: 'אירלנד' },
    { code: 'IL', label: 'ישראל' },
    { code: 'IM', label: 'האי מאן' },
    { code: 'IN', label: 'הודו' },
    { code: 'IO', label: 'טריטוריה בריטית באוקיינוס ההודי' },
    { code: 'IQ', label: 'עיראק' },
    { code: 'IR', label: 'איראן, רפובליקת' },
    { code: 'IS', label: 'איסלנד' },
    { code: 'IT', label: 'איטליה' },
    { code: 'JE', label: 'ג׳רזי' },
    { code: 'JM', label: 'ג׳מייקה' },
    { code: 'JO', label: 'ירדן' },
    { code: 'JP', label: 'יפן',  },
    { code: 'KE', label: 'קניה' },
    { code: 'KG', label: 'קירגיזסטן' },
    { code: 'KH', label: 'קמבודיה' },
    { code: 'KI', label: 'קיריבאטי' },
    { code: 'KM', label: 'קומורו' },
    { code: 'KN', label: 'סנט קיטס ונוויס' },
    { code: 'KP', label: 'קוריאה, קוריאה הדמוקרטית של' },
    { code: 'KR', label: 'קוריאה, קוריאה הרפובליקנית של' },
    { code: 'KW', label: 'כווית' },
    { code: 'KY', label: 'איי קיימן' },
    { code: 'KZ', label: 'קזחסטן' },
    { code: 'LA', label: 'לאוס, רפובליקת דמוקרטיה העם של' },
    { code: 'LB', label: 'לבנון' },
    { code: 'LC', label: 'סנט לוסיה' },
    { code: 'LI', label: 'ליכטנשטיין' },
    { code: 'LK', label: 'סרי לנקה' },
    { code: 'LR', label: 'ליבריה' },
    { code: 'LS', label: 'לסוטו' },
    { code: 'LT', label: 'ליטא' },
    { code: 'LU', label: 'לוקסמבורג' },
    { code: 'LV', label: 'לטביה' },
    { code: 'LY', label: 'לוב' },
    { code: 'MA', label: 'מרוקו' },
    { code: 'MC', label: 'מונקו' },
    { code: 'MD', label: 'מולדובה, רפובליקת' },
    { code: 'ME', label: 'מונטנגרו' },
    { code: 'MF', label: 'סן מרטן (חלק צרפתי)' },
    { code: 'MG', label: 'מדגסקר' },
    { code: 'MH', label: 'איי מרשל' },
    { code: 'MK', label: 'מקדוניה, רפובליקה היוונית הקודמת' },
    { code: 'ML', label: 'מאלי' },
    { code: 'MM', label: 'מיאנמר (בורמה)' },
    { code: 'MN', label: 'מונגוליה' },
    { code: 'MO', label: 'מקאו' },
    { code: 'MP', label: 'איי מריאנה הצפוניים' },
    { code: 'MQ', label: 'מרטיניק' },
    { code: 'MR', label: 'מאוריטניה' },
    { code: 'MS', label: 'מונסראט' },
    { code: 'MT', label: 'מלטה' },
    { code: 'MU', label: 'מאוריציוס' },
    { code: 'MV', label: 'האיים המלדיביים' },
    { code: 'MW', label: 'מלאווי' },
    { code: 'MX', label: 'מקסיקו' },
    { code: 'MY', label: 'מלזיה' },
    { code: 'MZ', label: 'מוזמביק' },
    { code: 'NA', label: 'נמיביה' },
    { code: 'NC', label: 'קלדוניה החדשה' },
    { code: 'NE', label: 'ניז׳ר' },
    { code: 'NF', label: 'איי נורפוק' },
    { code: 'NG', label: 'ניגריה' },
    { code: 'NI', label: 'ניקרגואה' },
    { code: 'NL', label: 'הולנד' },
    { code: 'NO', label: 'נורווגיה' },
    { code: 'NP', label: 'נפאל' },
    { code: 'NR', label: 'נאורו' },
    { code: 'NU', label: 'ניווה' },
    { code: 'NZ', label: 'ניו זילנד' },
    { code: 'OM', label: 'עומאן' },
    { code: 'PA', label: 'פנמה' },
    { code: 'PE', label: 'פרו' },
    { code: 'PF', label: 'פולינזיה הצרפתית' },
    { code: 'PG', label: 'פפואה גיניאה החדשה' },
    { code: 'PH', label: 'הפיליפינים' },
    { code: 'PK', label: 'פקיסטן' },
    { code: 'PL', label: 'פולין' },
    { code: 'PM', label: 'סן פייר ומיקלון' },
    { code: 'PN', label: 'פיטקרן' },
    { code: 'PR', label: 'פוארטו ריקו' },
    { code: 'PS', label: 'השטחים הפלסטיניים, מדינת' },
    { code: 'PT', label: 'פורטוגל' },
    { code: 'PW', label: 'פלאו' },
    { code: 'PY', label: 'פרגוואי' },
    { code: 'QA', label: 'קטאר' },
    { code: 'RE', label: 'ראוניון' },
    { code: 'RO', label: 'רומניה' },
    { code: 'RS', label: 'סרביה' },
    { code: 'RU', label: 'רוסיה' },
    { code: 'RW', label: 'רואנדה' },
    { code: 'SA', label: 'ערב הסעודית' },
    { code: 'SB', label: 'איי שלמה' },
    { code: 'SC', label: 'איי סיישל' },
    { code: 'SD', label: 'סודאן' },
    { code: 'SE', label: 'שוודיה' },
    { code: 'SG', label: 'סינגפור' },
    { code: 'SH', label: 'סנט הלנה' },
    { code: 'SI', label: 'סלובניה' },
    { code: 'SJ', label: 'סבאלברד ויאן מאיין' },
    { code: 'SK', label: 'סלובקיה' },
    { code: 'SL', label: 'סיירה ליאון' },
    { code: 'SM', label: 'סן מרינו' },
    { code: 'SN', label: 'סנגל' },
    { code: 'SO', label: 'סומליה' },
    { code: 'SR', label: 'סורינאם' },
    { code: 'SS', label: 'דרום סודאן' },
    { code: 'ST', label: 'סאו טומה ופרינסיפה' },
    { code: 'SV', label: 'אל סלבדור' },
    { code: 'SX', label: 'סינט מארטן (חלק הולנדי)' },
    { code: 'SY', label: 'סוריה' },
    { code: 'SZ', label: 'סווזילנד' },
    { code: 'TC', label: 'איי טרקס וקאיקוס' },
    { code: 'TD', label: 'צ׳אד' },
    { code: 'TF', label: 'טריטוריות דרומיות של צרפת' },
    { code: 'TG', label: 'טוגו' },
    { code: 'TH', label: 'תאילנד' },
    { code: 'TJ', label: 'טג׳יקיסטן' },
    { code: 'TK', label: 'טוקלאו' },
    { code: 'TL', label: 'מזרח טימור' },
    { code: 'TM', label: 'טורקמניסטן' },
    { code: 'TN', label: 'תוניסיה' },
    { code: 'TO', label: 'טונגה' },
    { code: 'TR', label: 'טורקיה' },
    { code: 'TT', label: 'טרינידד וטובגו' },
    { code: 'TV', label: 'טובאלו' },
    { code: 'TW', label: 'טייוואן, רפובליקה הסינית' },
    { code: 'TZ', label: 'תנזניה, הרפובליקה המאוחדת של' },
    { code: 'UA', label: 'אוקראינה' },
    { code: 'UG', label: 'אוגנדה' },
    { code: 'US', label: 'ארצות הברית',  },
    { code: 'UY', label: 'אורוגוואי' },
    { code: 'UZ', label: 'אוזבקיסטן' },
    { code: 'VA', label: 'הוותיקן (מדינת העיר הקדושה)' },
    { code: 'VC', label: 'סנט וינסנט והגרנדינים' },
    { code: 'VE', label: 'ונצואלה' },
    { code: 'VG', label: 'איי הבתולה הבריטיים' },
    { code: 'VI', label: 'איי הבתולה של ארצות הברית' },
    { code: 'VN', label: 'וייטנאם' },
    { code: 'VU', label: 'ונואטו' },
    { code: 'WF', label: 'וואליס ופוטונה' },
    { code: 'WS', label: 'סמואה' },
    { code: 'XK', label: 'קוסובו' },
    { code: 'YE', label: 'תימן' },
    { code: 'YT', label: 'מאיוט' },
    { code: 'ZA', label: 'דרום אפריקה' },
    { code: 'ZM', label: 'זמביה' },
    { code: 'ZW', label: 'זימבבואה' },
  ],
}

function countryData(local: string): CountryDataType[] {
  const countryData: CountryDataType[] = []
  for (const countryObj of countryDataBase) {
    const newObj: CountryDataType = { ...countryObj } // Create a shallow copy of the original object
    const matchinglabel = countriesLabels[local].find(
      (labelObj) => labelObj.code === newObj.code
    ) // Find the matching label object based on the code
    if (matchinglabel && matchinglabel.label) {
      newObj.label = matchinglabel.label // Add a new field with key "label" and value of the label in the local language
    }
    countryData.push(newObj) // Push the modified object to the new array
  }
  return countryData
}

export default countryData
